'use client';

import React, { useState } from 'react';
import { ModelResponse, ModelEvaluation } from '@/lib/types';
import { Copy, Check, ThumbsUp, ThumbsDown, Trophy, Code2, Columns2, LayoutList } from 'lucide-react';

interface AnswerComparisonProps {
  responses: ModelResponse[];
  evaluations: ModelEvaluation[];
  activeModelId: string;
  onSelectModel: (id: string) => void;
}

export const AnswerComparison: React.FC<AnswerComparisonProps> = ({
  responses,
  evaluations,
  activeModelId,
  onSelectModel,
}) => {
  const [viewMode, setViewMode] = useState<'side-by-side' | 'tabs'>('side-by-side');
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const handleCopy = (content: string, id: string) => {
    if (!content) return;
    navigator.clipboard.writeText(content);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  // Helper to render markdown-like content cleanly
  const renderFormattedContent = (content: string) => {
    if (!content) {
      return (
        <div className="py-8 text-center text-sm text-zinc-500">
          No answer generated or request failed for this model.
        </div>
      );
    }

    const sections = content.split(/(```[\s\S]*?```)/g);

    return sections.map((section, idx) => {
      if (section.startsWith('```')) {
        const firstLineEnd = section.indexOf('\n');
        const lang = section.slice(3, firstLineEnd).trim() || 'text';
        const code = section.slice(firstLineEnd + 1, -3);

        return (
          <div key={idx} className="my-2.5 overflow-hidden rounded-xl border border-zinc-800 bg-zinc-950">
            <div className="flex items-center justify-between border-b border-zinc-800/80 bg-zinc-900/90 px-3 py-1 text-xs text-zinc-400">
              <span className="flex items-center gap-1.5 font-mono text-[10px] uppercase">
                <Code2 className="h-3 w-3 text-indigo-400" />
                {lang}
              </span>
            </div>
            <pre className="overflow-x-auto p-3 font-mono text-xs leading-relaxed text-zinc-200">
              <code>{code}</code>
            </pre>
          </div>
        );
      }

      // Render standard text with headings and bold
      return (
        <div key={idx} className="space-y-2 text-xs sm:text-sm leading-relaxed text-zinc-300">
          {section.split('\n\n').map((para, pIdx) => {
            const trimmed = para.trim();
            if (!trimmed) return null;

            if (trimmed.startsWith('### ')) {
              return (
                <h3 key={pIdx} className="text-sm sm:text-base font-bold text-white pt-1.5">
                  {trimmed.replace('### ', '')}
                </h3>
              );
            }
            if (trimmed.startsWith('#### ')) {
              return (
                <h4 key={pIdx} className="text-xs sm:text-sm font-semibold text-zinc-100 pt-1">
                  {trimmed.replace('#### ', '')}
                </h4>
              );
            }
            if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
              const items = trimmed.split('\n');
              return (
                <ul key={pIdx} className="list-disc pl-4 space-y-1 text-zinc-300 text-xs sm:text-sm">
                  {items.map((it, itIdx) => (
                    <li key={itIdx}>{it.replace(/^[-*]\s*/, '')}</li>
                  ))}
                </ul>
              );
            }
            return <p key={pIdx} className="whitespace-pre-line">{trimmed}</p>;
          })}
        </div>
      );
    });
  };

  const activeResponse = responses.find((r) => r.modelId === activeModelId) || responses[0];
  const activeEval = evaluations.find((e) => e.modelId === activeModelId);

  return (
    <div id="answers-section" className="w-full space-y-4">
      {/* Section Header & View Mode Switcher */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-zinc-800 pb-3">
        <div>
          <h3 className="text-lg font-bold text-white flex items-center gap-2">
            <span>Model Answers Comparison</span>
            <span className="text-xs rounded-full bg-indigo-500/20 px-2 py-0.5 font-semibold text-indigo-300">
              {responses.length} Models
            </span>
          </h3>
          <p className="text-xs text-zinc-400">
            Read and compare the exact responses generated by each AI model.
          </p>
        </div>

        {/* View Toggle */}
        <div className="flex items-center gap-1 self-start sm:self-auto rounded-lg bg-zinc-900 p-1 border border-zinc-800">
          <button
            onClick={() => setViewMode('side-by-side')}
            className={`flex items-center gap-1.5 rounded-md px-2.5 py-1 text-xs font-medium transition-colors ${
              viewMode === 'side-by-side'
                ? 'bg-indigo-600 text-white shadow-sm'
                : 'text-zinc-400 hover:text-white'
            }`}
          >
            <Columns2 className="h-3.5 w-3.5" />
            <span>Side-by-Side</span>
          </button>
          <button
            onClick={() => setViewMode('tabs')}
            className={`flex items-center gap-1.5 rounded-md px-2.5 py-1 text-xs font-medium transition-colors ${
              viewMode === 'tabs'
                ? 'bg-indigo-600 text-white shadow-sm'
                : 'text-zinc-400 hover:text-white'
            }`}
          >
            <LayoutList className="h-3.5 w-3.5" />
            <span>Tabs View</span>
          </button>
        </div>
      </div>

      {/* 1. SIDE-BY-SIDE VIEW (Multi-column arena) */}
      {viewMode === 'side-by-side' && (
        <div
          className={`grid grid-cols-1 gap-4 ${
            responses.length === 2
              ? 'md:grid-cols-2'
              : responses.length >= 3
              ? 'lg:grid-cols-3'
              : 'grid-cols-1'
          }`}
        >
          {responses.map((resp) => {
            const ev = evaluations.find((e) => e.modelId === resp.modelId);
            const isWinner = ev?.rank === 1;

            return (
              <div
                key={resp.modelId}
                className={`flex flex-col rounded-2xl border bg-zinc-900/80 backdrop-blur-md overflow-hidden transition-all ${
                  isWinner
                    ? 'border-amber-500/50 shadow-lg shadow-amber-950/20 ring-1 ring-amber-500/30'
                    : 'border-zinc-800'
                }`}
              >
                {/* Column Card Header */}
                <div
                  className={`border-b p-3.5 flex items-center justify-between ${
                    isWinner
                      ? 'bg-gradient-to-r from-amber-950/40 via-zinc-900 to-zinc-900 border-amber-500/30'
                      : 'bg-zinc-950/80 border-zinc-800'
                  }`}
                >
                  <div>
                    <div className="flex items-center gap-1.5">
                      {isWinner && <Trophy className="h-4 w-4 text-amber-400 shrink-0" />}
                      <h4 className="font-bold text-sm text-white">{resp.modelName}</h4>
                    </div>
                    <div className="flex items-center gap-2 text-[11px] text-zinc-400 mt-0.5">
                      <span>{resp.provider}</span>
                      <span>•</span>
                      <span>{resp.latencyMs ? `${resp.latencyMs}ms` : 'N/A'}</span>
                    </div>
                  </div>

                  <div className="flex items-center gap-2">
                    {ev && (
                      <span
                        className={`rounded-lg px-2 py-1 text-xs font-bold ${
                          isWinner
                            ? 'bg-amber-500/20 text-amber-300 ring-1 ring-amber-500/40'
                            : 'bg-zinc-800 text-zinc-200'
                        }`}
                      >
                        {ev.overallScore}★
                      </span>
                    )}
                    <button
                      onClick={() => handleCopy(resp.content, resp.modelId)}
                      className="rounded-lg p-1.5 text-zinc-400 hover:bg-zinc-800 hover:text-white transition-colors"
                      title="Copy this answer"
                    >
                      {copiedId === resp.modelId ? (
                        <Check className="h-3.5 w-3.5 text-emerald-400" />
                      ) : (
                        <Copy className="h-3.5 w-3.5" />
                      )}
                    </button>
                  </div>
                </div>

                {/* Actual Generated Answer Body */}
                <div className="flex-1 p-4 overflow-y-auto max-h-[600px] space-y-3">
                  {renderFormattedContent(resp.content)}
                </div>

                {/* Judge Pros & Cons footer */}
                {ev && (
                  <div className="border-t border-zinc-800/80 bg-zinc-950/70 p-3 text-[11px] space-y-1.5">
                    <div className="font-semibold text-zinc-300 flex items-center justify-between">
                      <span className="text-zinc-400">Judge Rating:</span>
                      <span className="text-indigo-400 font-bold">Rank #{ev.rank}</span>
                    </div>
                    {ev.strengths[0] && (
                      <div className="flex items-start gap-1 text-emerald-400">
                        <ThumbsUp className="h-3 w-3 shrink-0 mt-0.5" />
                        <span className="text-zinc-300 leading-tight">{ev.strengths[0]}</span>
                      </div>
                    )}
                    {ev.weaknesses[0] && (
                      <div className="flex items-start gap-1 text-amber-400">
                        <ThumbsDown className="h-3 w-3 shrink-0 mt-0.5" />
                        <span className="text-zinc-300 leading-tight">{ev.weaknesses[0]}</span>
                      </div>
                    )}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}

      {/* 2. TABS VIEW (Single model focus) */}
      {viewMode === 'tabs' && (
        <div className="rounded-2xl border border-zinc-800 bg-zinc-900/70 backdrop-blur-md overflow-hidden">
          {/* Tab Navigation */}
          <div className="flex overflow-x-auto border-b border-zinc-800 bg-zinc-950/60 p-1.5 scrollbar-none">
            {responses.map((resp) => {
              const ev = evaluations.find((e) => e.modelId === resp.modelId);
              const isSelected = activeModelId === resp.modelId;
              const isWinner = ev?.rank === 1;

              return (
                <button
                  key={resp.modelId}
                  onClick={() => onSelectModel(resp.modelId)}
                  className={`flex items-center gap-2 whitespace-nowrap rounded-xl px-4 py-2 text-xs font-semibold transition-all ${
                    isSelected
                      ? 'bg-zinc-800 text-white shadow-sm ring-1 ring-zinc-700'
                      : 'text-zinc-400 hover:bg-zinc-900 hover:text-zinc-200'
                  }`}
                >
                  {isWinner && <Trophy className="h-3.5 w-3.5 text-amber-400" />}
                  <span>{resp.modelName}</span>
                  {ev && (
                    <span
                      className={`rounded px-1.5 py-0.5 text-[10px] font-bold ${
                        isWinner ? 'bg-amber-500/20 text-amber-300' : 'bg-zinc-800 text-zinc-300'
                      }`}
                    >
                      {ev.overallScore}★
                    </span>
                  )}
                </button>
              );
            })}
          </div>

          {/* Answer Content & Judge Analysis */}
          <div className="p-4 sm:p-6 space-y-6">
            <div className="flex items-center justify-between border-b border-zinc-800/80 pb-3">
              <div>
                <h3 className="font-bold text-base text-white">{activeResponse?.modelName}</h3>
                <p className="text-xs text-zinc-400">
                  Provider: {activeResponse?.provider} • Latency:{' '}
                  {activeResponse?.latencyMs ? `${activeResponse.latencyMs}ms` : 'N/A'}
                </p>
              </div>

              <button
                onClick={() =>
                  activeResponse?.content && handleCopy(activeResponse.content, activeResponse.modelId)
                }
                className="flex items-center gap-1.5 rounded-lg border border-zinc-800 bg-zinc-900 px-3 py-1.5 text-xs font-medium text-zinc-300 transition-colors hover:bg-zinc-800 hover:text-white"
              >
                {copiedId === activeResponse?.modelId ? (
                  <>
                    <Check className="h-3.5 w-3.5 text-emerald-400" />
                    <span className="text-emerald-400">Copied!</span>
                  </>
                ) : (
                  <>
                    <Copy className="h-3.5 w-3.5" />
                    <span>Copy Answer</span>
                  </>
                )}
              </button>
            </div>

            {/* Formatted Model Answer */}
            <div className="space-y-4">{renderFormattedContent(activeResponse?.content || '')}</div>

            {/* Judge Feedback Box */}
            {activeEval && (
              <div className="mt-6 rounded-xl border border-zinc-800 bg-zinc-950/60 p-4 space-y-3">
                <h4 className="text-xs font-bold uppercase tracking-wider text-zinc-400">
                  Judge Evaluation for {activeEval.modelName}
                </h4>

                <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                  <div className="space-y-1.5">
                    <div className="flex items-center gap-1.5 text-xs font-semibold text-emerald-400">
                      <ThumbsUp className="h-3.5 w-3.5" />
                      Key Strengths
                    </div>
                    <ul className="list-disc pl-4 text-xs text-zinc-300 space-y-1">
                      {activeEval.strengths.map((str, idx) => (
                        <li key={idx}>{str}</li>
                      ))}
                    </ul>
                  </div>

                  <div className="space-y-1.5">
                    <div className="flex items-center gap-1.5 text-xs font-semibold text-amber-400">
                      <ThumbsDown className="h-3.5 w-3.5" />
                      Points for Improvement
                    </div>
                    <ul className="list-disc pl-4 text-xs text-zinc-300 space-y-1">
                      {activeEval.weaknesses.map((weak, idx) => (
                        <li key={idx}>{weak}</li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};
